#!/usr/bin/env python3
"""
Setup Auto Version Bump on Git Commits

This script installs a Git pre-commit hook that automatically
bumps the patch version before each commit.

Usage:
    python setup_auto_version.py [install|uninstall]
"""

import sys
import os
from pathlib import Path
import shutil


HOOK_CONTENT = """#!/usr/bin/env python3
# Auto Version Bump Pre-Commit Hook
# Generated by setup_auto_version.py

import sys
import os
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent.parent / "System Scanner"
sys.path.insert(0, str(project_root))

try:
    from scanner.version_manager import increment_version, get_version
    
    old_version = get_version()
    new_version = increment_version("patch")
    
    print(f"[Auto Version] {old_version} -> {new_version}")
    
    # Stage the updated version file
    os.system('git add "System Scanner/scanner/version_manager.py"')
    os.system('git add "System Scanner/version_history.json"')
    
except Exception as e:
    print(f"[Auto Version] Warning: Failed to bump version: {e}")
    # Don't block the commit
    pass

sys.exit(0)
"""


def install_hook():
    """Install the auto version bump pre-commit hook."""
    git_dir = Path(__file__).parent.parent / ".git"
    
    if not git_dir.exists():
        print("Error: .git directory not found!")
        print("Make sure you're in a Git repository.")
        return 1
    
    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    
    hook_file = hooks_dir / "pre-commit"
    
    if hook_file.exists():
        # Backup existing hook
        backup_file = hooks_dir / "pre-commit.backup"
        shutil.copy(hook_file, backup_file)
        print(f"✓ Backed up existing pre-commit hook to: {backup_file}")
    
    # Write new hook
    hook_file.write_text(HOOK_CONTENT, encoding="utf-8")
    
    # Make executable (Unix-like systems)
    if os.name != 'nt':
        os.chmod(hook_file, 0o755)
    
    print("\n" + "=" * 60)
    print("AUTO VERSION BUMP HOOK INSTALLED")
    print("=" * 60)
    print(f"Location: {hook_file}")
    print("\nThe version will now auto-increment (patch) on every commit.")
    print("\nTo manually control version bumps:")
    print("  python auto_version_bump.py patch   # Bug fixes")
    print("  python auto_version_bump.py minor   # New features")
    print("  python auto_version_bump.py major   # Breaking changes")
    print("=" * 60)
    print()
    
    return 0


def uninstall_hook():
    """Uninstall the auto version bump pre-commit hook."""
    git_dir = Path(__file__).parent.parent / ".git"
    
    if not git_dir.exists():
        print("Error: .git directory not found!")
        return 1
    
    hook_file = git_dir / "hooks" / "pre-commit"
    backup_file = git_dir / "hooks" / "pre-commit.backup"
    
    if not hook_file.exists():
        print("No pre-commit hook found to uninstall.")
        return 0
    
    # Check if it's our hook
    content = hook_file.read_text(encoding="utf-8")
    if "Auto Version Bump Pre-Commit Hook" not in content:
        print("Warning: pre-commit hook exists but is not the auto-version hook.")
        print("Not removing to preserve your custom hook.")
        return 1
    
    # Remove hook
    hook_file.unlink()
    print(f"✓ Removed auto-version hook: {hook_file}")
    
    # Restore backup if exists
    if backup_file.exists():
        shutil.move(backup_file, hook_file)
        print(f"✓ Restored previous hook from backup")
    
    print("\nAuto version bump disabled.")
    return 0


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("\nUsage: python setup_auto_version.py [install|uninstall]")
        print("\n  install   - Install auto version bump on Git commits")
        print("  uninstall - Remove auto version bump hook")
        print()
        return 1
    
    action = sys.argv[1].lower()
    
    if action == "install":
        return install_hook()
    elif action == "uninstall":
        return uninstall_hook()
    else:
        print(f"Error: Unknown action '{action}'")
        print("Valid actions: install, uninstall")
        return 1


if __name__ == "__main__":
    sys.exit(main())
